name: Android

on:
  push:
    branches:
      #- develop
      #- 'release/*'

jobs:
  test:
    runs-on: ubuntu-18.04
  steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.12.13+hotfix.8'
    - name: Flutter Doctor
      run: flutter doctor
    - name: IntegrationTest(database)
      run: |
        cd example
        flutter driver --target=test_driver/realm_database.dart